### ISSUE TITLE
Daikin altherma EAVH16S23DA6V model 

### ISSUE THREAD

**Issue by Sigmun** [Arnold-n/P1P2MQTT#138]
Hi,

I have a Daikin Altherma heating and cooling system. Inter al unit is a EAVH16S23DA6V model. How do you think it can be managed? 

Thanks for your answer, I need a way to use correctly my system which does not seem to use correctly the pump system to heat when my command temperature is under 25°C which is way to high for my house.

**Comment by Arnold-n** [comment]
Sound like your heating system is very efficient! Unfortunately Daikin heat pumps are not able to generate leaving water temperature below 25°C using the compressor. It will use the backup heater instead. It has been suggested that this is either to prevent short-cycling or due to physical limitations of the heat pump. It seems your only solution would be to set the LWT setpoint at 25°C and either mix it down to your target temperature or to accept 25°C and switch the compressor on/off (which can be done using the thermostat or using the P1P2MQTT bridge).
